### ISSUE TITLE
getenvoy fetch/list failing with net/http: TLS handshake timeout 

### ISSUE THREAD

**Issue by anupam128** [tetratelabs/getenvoy#120] opened 2021-03-16 05:16 UTC
**Describe the bug**
All getenvoy operations are failing with net/http: TLS handshake timeout 

**To Reproduce**
```
> curl -s -L https://getenvoy.io/cli | bash -s -- -b .
> ./getenvoy fetch standard:1.16.1
tetratelabs/getenvoy info checking GitHub for latest tag
tetratelabs/getenvoy info found version: 0.2.1 for v0.2.1/Darwin/x86_64
tetratelabs/getenvoy info installed ./getenvoy
Error: Get https://tetrate.bintray.com/getenvoy/manifest.json: net/http: TLS handshake timeout 
```

**Expected behavior**
It should not fail.

**Environment (please complete the relevant information):**
 - OS: [Ubuntu 18:04 and MacOS 11.2]

**Additional context**
Issue started after 11:00 pm March 15th UTC.

**Comment by anupam128** [comment] 2021-03-16 16:43
This issue is resolved now.
Linking #113 as there should probably a move to some alternative?

**Comment by codefromthecrypt** [comment] 2021-03-26 02:55
closing because it is indeed a duplicate of the known issue  #113, not because we've solved it yet. thanks for reporting!

**Closed by codefromthecrypt** 2021-03-26 02:55 UTC
Labels: bug
